### ISSUE TITLE
Reporting of Statistics for Smoothed Data

### ISSUE THREAD

**Issue by kintigh** [openskope/skopeui#114] opened 2021-06-25 19:07 UTC
The original data statistics should be the same for the same area and time selection whether or not the data are smoothed (I.e. don't include the extra years needed to do the smoothing in the reported statistics calculation.  Now they can be different.  This is the case _whether or not there is a Z-Score Transformation_

there is a related but  separate issue:  with smoothed Z score transformed data,  using the selected time range vs a fixed time range set to the same values should produce the same result.  Now different time ranges are used in the calcuation of the mean and sd for the two cases.  Only the years within the interval should be used for mean and SD calculation.

**Comment by alee** [comment] 2021-11-30 20:38
this is a duplicate of https://github.com/openskope/skope-api/issues/20 - closing in favor of the skope-api issue as that is where the problem originates

**Closed by alee** 2021-11-30 20:38 UTC
